### ISSUE TITLE
Mojo/UserAgent.pm issues

### ISSUE THREAD

**Issue by ehrzuli** [vsTerminus/Discord-NP#17]
Hi there, I'm encountering this error when I run discordnp.exe on Windows 10:

Tue Dec 1 20:15:29 2020 - Loaded Config: config.ini
Use of unauthorized value $loop in hash element at Mojo/UserAgent.pm line 192.
Mojo:: Reactor::Poll: I/O watcher failed: Can't call method "remove" on an undefined value at Mojo/UserAgent.pm line 269.

Here are the steps I've taken leading up to this:
- Created last.fm API account and acquired API key
- Acquired Discord token
- Downloaded the latest .exe
- Extracted file to a folder titled "Discord-NP" in /AppData/Local (same place my Discord folder is)
- Entered all the necessary information into config.ini.example and saved as config.ini
- Ran discordnp.exe

I've been able to get another Discord scrobbler to work, so I know the Discord token is correct. I'd just rather use this one if I can because it looks so nice.

Thanks in advance.

**Comment by vsTerminus** [comment]
Hey, sorry you're having trouble. I'm not entirely sure what the issue is, but I compiled a new version of the application today that runs my latest discord and lastfm code plus adds some validation on the config file.

Could you try updating and see if it solves your problem? https://github.com/vsTerminus/Discord-NP/releases/tag/1.3

If that doesn't do it, there is a log file that might be able to help you:

1. Open your "config.ini" and set "log_level=debug" at the bottom of the file
2. Run the application
3. Look inside "mojo-discord.log" in the same folder where your exe is

Don't share this file, it will log your Discord User Token. (I'll remove that in a future update) But it might help you figure out what's going on.

Let me know how it goes.

**Comment by ehrzuli** [comment]
Your new version worked perfectly! It looks great in Discord. Thank you so much for your awesome work.
