### ISSUE TITLE
Last.FM Lookup failed

### ISSUE THREAD

**Issue by jscott5811** [vsTerminus/Discord-NP#28]
Cannot send OP Client is not connected at gateway.pm line 302

**Comment by vsTerminus** [comment]
In `config.ini` set `log_level = debug` and `log_dir = .` and try again.

It should generate a file named `mojo-discord.log`.

You can either share that file here with me or look through it yourself and see if it sheds any more light on the problem.

- Was it working before and now it doesn't?
- Or are you setting it up for the first time?

**Comment by jscott5811** [comment]
It was working before and now it doesn't and i haven't changed anything recently
[mojo-discord.log](https://github.com/vsTerminus/Discord-NP/files/9113638/mojo-discord.log)
.

**Comment by vsTerminus** [comment]
`[2022-07-14 12:35:35.51677] [7928] [info] [Gateway.pm] [on_finish] Websocket connection closed with Code $code = 4004;
 (Authentication failed.)`

Likely your token has expired or otherwise been changed. This is common when you log in with a new device for the first time, change MFA settings, and on other events.

Try getting a new copy of your Discord token and see if that works for you!

**Comment by jscott5811** [comment]
Updated the discord token and it seems to be working again!

**Comment by vsTerminus** [comment]
Great!

You can disable the logging by changing the log level back to `fatal`.
